/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLogin.java
 *
 * Created on 05/11/2009, 12:11:20
 */

package sapo.view;

import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import sapo.controller.ControleOrientador;
import sapo.model.OrientadorModelo;

/**
 *
 * @author wsouza
 */
public class DlgLogin extends javax.swing.JDialog {

    /** Creates new form DlgLogin */
    private OrientadorModelo orientador;
    ControleOrientador controle;

    public DlgLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setActionComand();
    }

    private void setActionComand(){
        jbtnLogin.setActionCommand("LOGIN");
        jbtnCancelar.setActionCommand("CANCEL_LOGIN");   
        orientador = new OrientadorModelo();
        controle = new ControleOrientador(orientador, this);
    }

    public JPasswordField getJpsfSenha() {
        return jpsfSenha;
    }

    public void setJpsfSenha(JPasswordField jpsfSenha) {
        this.jpsfSenha = jpsfSenha;
    }

    public JButton getJbtnCancelar() {
        return jbtnCancelar;
    }

    public void setJbtnCancelar(JButton jbtnCancelar) {
        this.jbtnCancelar = jbtnCancelar;
    }

    public JButton getJbtnLogin() {
        return jbtnLogin;
    }

    public void setJbtnLogin(JButton jbtnLogin) {
        this.jbtnLogin = jbtnLogin;
    }

    public JFormattedTextField getJftfUsuario() {
        return jftfUsuario;
    }

    public void setJftfUsuario(JFormattedTextField jftfUsuario) {
        this.jftfUsuario = jftfUsuario;
    }

    public JPanel getJpnlAtribs() {
        return jpnlAtribs;
    }

    public void setJpnlAtribs(JPanel jpnlAtribs) {
        this.jpnlAtribs = jpnlAtribs;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnlTitulo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpnlCorpo = new javax.swing.JPanel();
        jpnlBotoes = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpnlAtribs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jftfUsuario = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jpsfSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jpnlTitulo.setLayout(new java.awt.GridBagLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_login_topo2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jpnlTitulo.add(jLabel6, gridBagConstraints);

        getContentPane().add(jpnlTitulo, java.awt.BorderLayout.PAGE_START);

        jpnlCorpo.setLayout(new java.awt.BorderLayout());

        jpnlBotoes.setLayout(new java.awt.GridBagLayout());

        jbtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_login.png"))); // NOI18N
        jbtnLogin.setBorderPainted(false);
        jbtnLogin.setContentAreaFilled(false);
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 20);
        jpnlBotoes.add(jbtnLogin, gridBagConstraints);

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_cancelar.png"))); // NOI18N
        jbtnCancelar.setBorderPainted(false);
        jbtnCancelar.setContentAreaFilled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 200);
        jpnlBotoes.add(jbtnCancelar, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_login_baixo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jpnlBotoes.add(jLabel1, gridBagConstraints);

        jpnlCorpo.add(jpnlBotoes, java.awt.BorderLayout.PAGE_END);

        jpnlAtribs.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Usuário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpnlAtribs.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpnlAtribs.add(jftfUsuario, gridBagConstraints);

        jLabel4.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpnlAtribs.add(jLabel4, gridBagConstraints);

        jpsfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpsfSenhaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpnlAtribs.add(jpsfSenha, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_login_centro.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(-100, -100, -100, -100);
        jpnlAtribs.add(jLabel5, gridBagConstraints);

        jpnlCorpo.add(jpnlAtribs, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnlCorpo, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-494)/2, (screenSize.height-330)/2, 494, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jpsfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpsfSenhaKeyPressed
        //System.out.println(String.valueOf(evt.hashCode()));
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbtnLogin.doClick();
        }
    }//GEN-LAST:event_jpsfSenhaKeyPressed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JFormattedTextField jftfUsuario;
    private javax.swing.JPanel jpnlAtribs;
    private javax.swing.JPanel jpnlBotoes;
    private javax.swing.JPanel jpnlCorpo;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JPasswordField jpsfSenha;
    // End of variables declaration//GEN-END:variables

}
