/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlAluno.java
 *
 * Created on 21/10/2009, 23:15:37
 */
package sapo.view;

import java.awt.Color;
import sapo.util.Mascara;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author christino
 */
public class PnlAluno extends javax.swing.JPanel {

    Mascara masc = new Mascara();

    /** Creates new form PnlAluno */
    public PnlAluno() {

        initComponents();
        try {
            MaskFormatter mData = masc.getMaskData();
            MaskFormatter mCep = masc.getMaskCep();
            MaskFormatter mTel = masc.getMaskTel();
            MaskFormatter mNome = masc.getMaskTexto(40);
            MaskFormatter mRua = masc.getMaskTexto(30);
            MaskFormatter mBairro = masc.getMaskTexto(20);
            MaskFormatter mCidade = masc.getMaskTexto(25);
            MaskFormatter mNroRua = masc.getMaskNumero(5);
            mData.install(jftfDataNasc);
            mCep.install(jftfCEP);
            mTel.install(jftfTelefone);
            mNome.install(jftfNome);
            mRua.install(jftfRua);
            mBairro.install(jftfBairro);
            mCidade.install(jftfCidade);
            mNroRua.install(jftfNroRua);

            masc.trim(jftfDataNasc);
            masc.trim(jftfCEP);
            masc.trim(jftfTelefone);
            masc.trim(jftfNome);
            masc.trim(jftfRua);
            masc.trim(jftfBairro);
            masc.trim(jftfCidade);
            masc.trim(jftfMatricula);
            masc.trim(jftfNroRua);



        } catch (ParseException ex) {
            Logger.getLogger(PnlAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void validaCampo(JFormattedTextField f) {
        /*if (f.getText().trim().equals("")) {
            f.setText("0");
            f.setBackground(Color.green);
        } else {
            if (!(f.getText().equals("0"))) {
                f.setBackground(Color.white);
                f.setText(f.getText().toUpperCase());
            }
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public JLabel getJLblBairro() {
        return jLblBairro;

    }

    public void setJLblBairro(JLabel jLblBairro) {
        this.jLblBairro = jLblBairro;
    }

    public JLabel getJLblCEP() {
        return jLblCEP;
    }

    public void setJLblCEP(JLabel jLblCEP) {
        this.jLblCEP = jLblCEP;
    }

    public JLabel getJLblCidade() {
        return jLblCidade;
    }

    public void setJLblCidade(JLabel jLblCidade) {
        this.jLblCidade = jLblCidade;
    }

    public JLabel getJLblDataNasc() {
        return jLblDataNasc;
    }

    public void setJLblDataNasc(JLabel jLblDataNasc) {
        this.jLblDataNasc = jLblDataNasc;
    }

    public JLabel getJLblMatricula() {
        return jLblMatricula;
    }

    public void setJLblMatricula(JLabel jLblMatricula) {
        this.jLblMatricula = jLblMatricula;
    }

    public JLabel getJLblNome() {
        return jLblNome;
    }

    public void setJLblNome(JLabel jLblNome) {
        this.jLblNome = jLblNome;
    }

    public JLabel getJLblNroRua() {
        return jLblNroRua;
    }

    public void setJLblNroRua(JLabel jLblNroRua) {
        this.jLblNroRua = jLblNroRua;
    }

    public JLabel getJLblRua() {
        return jLblRua;
    }

    public void setJLblRua(JLabel jLblRua) {
        this.jLblRua = jLblRua;
    }

    public JLabel getJLblTelefone() {
        return jLblTelefone;
    }

    public void setJLblTelefone(JLabel jLblTelefone) {
        this.jLblTelefone = jLblTelefone;
    }

    public JFormattedTextField getJftCEP() {
        return jftfCEP;
    }

    public void setJftCEP(JFormattedTextField jftCEP) {
        this.jftfCEP = jftCEP;
    }

    public JFormattedTextField getJftDataNasc() {
        return jftfDataNasc;
    }

    public void setJftDataNasc(JFormattedTextField jftDataNasc) {
        this.jftfDataNasc = jftDataNasc;
    }

    public JFormattedTextField getJftTelefone() {
        return jftfTelefone;
    }

    public void setJftTelefone(JFormattedTextField jftTelefone) {
        this.jftfTelefone = jftTelefone;
    }

    public JFormattedTextField getJtfBairro() {
        return jftfBairro;
    }

    public void setJtfBairro(JFormattedTextField jtfBairro) {
        this.jftfBairro = jtfBairro;
    }

    public JFormattedTextField getJtfCidade() {
        return jftfCidade;
    }

    public void setJtfCidade(JFormattedTextField jtfCidade) {
        this.jftfCidade = jtfCidade;
    }

    public JFormattedTextField getJtfMatricula() {
        return jftfMatricula;
    }

    public void setJtfMatricula(JFormattedTextField jtfMatricula) {
        this.jftfMatricula = jtfMatricula;
    }

    public JFormattedTextField getJftNome() {
        return jftfNome;
    }

    public void setJftNome(JFormattedTextField jftNome) {
        this.jftfNome = jftNome;
    }

    public JFormattedTextField getJtfNroRua() {
        return jftfNroRua;
    }

    public void setJtfNroRua(JFormattedTextField jtfNroRua) {
        this.jftfNroRua = jtfNroRua;
    }

    public JFormattedTextField getJtfRua() {
        return jftfRua;
    }

    public void setJtfRua(JFormattedTextField jtfRua) {
        this.jftfRua = jtfRua;
    }

    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLblMatricula = new javax.swing.JLabel();
        jLblRua = new javax.swing.JLabel();
        jLblNroRua = new javax.swing.JLabel();
        jLblBairro = new javax.swing.JLabel();
        jLblCidade = new javax.swing.JLabel();
        jLblDataNasc = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jLblCEP = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jftfDataNasc = new javax.swing.JFormattedTextField();
        jftfCEP = new javax.swing.JFormattedTextField();
        jlblClassificacao = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jftfNome = new javax.swing.JFormattedTextField();
        jftfCidade = new javax.swing.JFormattedTextField();
        jftfBairro = new javax.swing.JFormattedTextField();
        jftfRua = new javax.swing.JFormattedTextField();
        jftfNroRua = new javax.swing.JFormattedTextField();
        jftfMatricula = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLblMatricula.setText("Matricula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 40, 2);
        add(jLblMatricula, gridBagConstraints);

        jLblRua.setText("Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblRua, gridBagConstraints);

        jLblNroRua.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblNroRua, gridBagConstraints);

        jLblBairro.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblBairro, gridBagConstraints);

        jLblCidade.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblCidade, gridBagConstraints);

        jLblDataNasc.setText("Data Nasc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblDataNasc, gridBagConstraints);

        jLblTelefone.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblTelefone, gridBagConstraints);

        jLblCEP.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblCEP, gridBagConstraints);

        jLblNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblNome, gridBagConstraints);

        jftfTelefone.setColumns(10);
        jftfTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfTelefoneMouseClicked(evt);
            }
        });
        jftfTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfTelefoneFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfTelefone, gridBagConstraints);

        jftfDataNasc.setColumns(10);
        jftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jftfDataNasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfDataNascMouseClicked(evt);
            }
        });
        jftfDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfDataNascFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfDataNascFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfDataNasc, gridBagConstraints);

        jftfCEP.setColumns(10);
        jftfCEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfCEPMouseClicked(evt);
            }
        });
        jftfCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfCEPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfCEPFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfCEP, gridBagConstraints);

        jlblClassificacao.setText("Classificação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jlblClassificacao, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Leve", "Moderada", "Severa" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jComboBox1, gridBagConstraints);

        jftfNome.setColumns(20);
        jftfNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfNomeMouseClicked(evt);
            }
        });
        jftfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfNomeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfNome, gridBagConstraints);

        jftfCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfCidadeMouseClicked(evt);
            }
        });
        jftfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfCidadeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfCidade, gridBagConstraints);

        jftfBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfBairroMouseClicked(evt);
            }
        });
        jftfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfBairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfBairroFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfBairro, gridBagConstraints);

        jftfRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfRuaMouseClicked(evt);
            }
        });
        jftfRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfRuaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfRua, gridBagConstraints);

        jftfNroRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfNroRuaMouseClicked(evt);
            }
        });
        jftfNroRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfNroRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfNroRuaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfNroRua, gridBagConstraints);

        jftfMatricula.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 40, 2);
        add(jftfMatricula, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_painel_aluno.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jftfNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfNomeMouseClicked
        jftfNome.setText(jftfNome.getText().trim());
    }//GEN-LAST:event_jftfNomeMouseClicked

    private void jftfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNomeFocusGained
        jftfNome.setText(jftfNome.getText().trim());
    }//GEN-LAST:event_jftfNomeFocusGained

    private void jftfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNomeFocusLost
        jftfNome.setText(jftfNome.getText().trim());
        validaCampo(jftfNome);
    }//GEN-LAST:event_jftfNomeFocusLost

    private void jftfDataNascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfDataNascFocusGained
        jftfDataNasc.setText(jftfDataNasc.getText().trim());
    }//GEN-LAST:event_jftfDataNascFocusGained

    private void jftfDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfDataNascFocusLost
        jftfDataNasc.setText(jftfDataNasc.getText().trim());
        validaCampo(jftfDataNasc);
    }//GEN-LAST:event_jftfDataNascFocusLost

    private void jftfDataNascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfDataNascMouseClicked
        jftfDataNasc.setText(jftfDataNasc.getText().trim());
    }//GEN-LAST:event_jftfDataNascMouseClicked

    private void jftfCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfCidadeMouseClicked
        jftfCidade.setText(jftfCidade.getText().trim());
    }//GEN-LAST:event_jftfCidadeMouseClicked

    private void jftfCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCidadeFocusLost
        jftfCidade.setText(jftfCidade.getText().trim());
        validaCampo(jftfCidade);
    }//GEN-LAST:event_jftfCidadeFocusLost

    private void jftfCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCidadeFocusGained
        jftfCidade.setText(jftfCidade.getText().trim());
    }//GEN-LAST:event_jftfCidadeFocusGained

    private void jftfBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfBairroFocusGained
        jftfBairro.setText(jftfBairro.getText().trim());
    }//GEN-LAST:event_jftfBairroFocusGained

    private void jftfBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfBairroFocusLost
        jftfBairro.setText(jftfBairro.getText().trim());
        validaCampo(jftfBairro);
    }//GEN-LAST:event_jftfBairroFocusLost

    private void jftfBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfBairroMouseClicked
        jftfBairro.setText(jftfBairro.getText().trim());
    }//GEN-LAST:event_jftfBairroMouseClicked

    private void jftfRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfRuaMouseClicked
        jftfRua.setText(jftfRua.getText().trim());
    }//GEN-LAST:event_jftfRuaMouseClicked

    private void jftfRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfRuaFocusLost
        jftfRua.setText(jftfRua.getText().trim());
        validaCampo(jftfRua);
    }//GEN-LAST:event_jftfRuaFocusLost

    private void jftfRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfRuaFocusGained
        jftfRua.setText(jftfRua.getText().trim());
    }//GEN-LAST:event_jftfRuaFocusGained

    private void jftfTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfTelefoneFocusGained
        jftfTelefone.setText(jftfTelefone.getText().trim());
    }//GEN-LAST:event_jftfTelefoneFocusGained

    private void jftfTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfTelefoneFocusLost
        jftfTelefone.setText(jftfTelefone.getText().trim());
        validaCampo(jftfTelefone);
    }//GEN-LAST:event_jftfTelefoneFocusLost

    private void jftfTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfTelefoneMouseClicked
        jftfTelefone.setText(jftfTelefone.getText().trim());
    }//GEN-LAST:event_jftfTelefoneMouseClicked

    private void jftfCEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCEPFocusGained
        jftfCEP.setText(jftfCEP.getText().trim());
    }//GEN-LAST:event_jftfCEPFocusGained

    private void jftfCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCEPFocusLost
        jftfCEP.setText(jftfCEP.getText().trim());
        validaCampo(jftfCEP);
    }//GEN-LAST:event_jftfCEPFocusLost

    private void jftfCEPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfCEPMouseClicked
        jftfCEP.setText(jftfCEP.getText().trim());
    }//GEN-LAST:event_jftfCEPMouseClicked

    private void jftfNroRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNroRuaFocusGained
        jftfNroRua.setText(jftfNroRua.getText().trim());
    }//GEN-LAST:event_jftfNroRuaFocusGained

    private void jftfNroRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNroRuaFocusLost
        jftfNroRua.setText(jftfNroRua.getText().trim());
        validaCampo(jftfNroRua);
    }//GEN-LAST:event_jftfNroRuaFocusLost

    private void jftfNroRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfNroRuaMouseClicked
        jftfNroRua.setText(jftfNroRua.getText().trim());
    }//GEN-LAST:event_jftfNroRuaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblDataNasc;
    private javax.swing.JLabel jLblMatricula;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNroRua;
    private javax.swing.JLabel jLblRua;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JFormattedTextField jftfBairro;
    private javax.swing.JFormattedTextField jftfCEP;
    private javax.swing.JFormattedTextField jftfCidade;
    private javax.swing.JFormattedTextField jftfDataNasc;
    private javax.swing.JFormattedTextField jftfMatricula;
    private javax.swing.JFormattedTextField jftfNome;
    private javax.swing.JFormattedTextField jftfNroRua;
    private javax.swing.JFormattedTextField jftfRua;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JLabel jlblClassificacao;
    // End of variables declaration//GEN-END:variables
}
