/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlOperador.java
 *
 * Created on 21/10/2009, 23:42:29
 */

package sapo.view;

import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author christino
 */
public class PnlOperador extends javax.swing.JPanel {

    /** Creates new form PnlOperador */
    public PnlOperador() {
        initComponents();
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLblSenha = new javax.swing.JLabel();
        jLblUsuario = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLblSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(-30, 5, 0, 5);
        add(jLblSenha, gridBagConstraints);

        jLblUsuario.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 5);
        add(jLblUsuario, gridBagConstraints);

        jtfMatricula.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jtfMatricula, gridBagConstraints);

        jPFSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFSenhaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(-30, 0, 0, 0);
        add(jPFSenha, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_painel_operador.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jtfMatricula;
    // End of variables declaration//GEN-END:variables

    public JPasswordField getjPFSenha() {
        return jPFSenha;
    }

    public void setjPFSenha(JPasswordField jPFSenha) {
        this.jPFSenha = jPFSenha;
    }

    public JTextField getJtfMatricula() {
        return jtfMatricula;
    }

    public void setJtfMatricula(JTextField jtfMatricula) {
        this.jtfMatricula = jtfMatricula;
    }

}
