/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlAluno.java
 *
 * Created on 21/10/2009, 23:15:37
 */
package sapo.view;

import java.awt.Color;
import sapo.util.Mascara;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author christino
 */
public class PnlOrientador extends javax.swing.JPanel {

    private Mascara masc = new Mascara();

    /** Creates new form PnlAluno */
    public PnlOrientador() {
        initComponents();
        try {
            MaskFormatter mNome = masc.getMaskTexto(40);
            MaskFormatter mRua = masc.getMaskTexto(30);
            MaskFormatter mNroRua = masc.getMaskNumero(5);
            MaskFormatter mBairro = masc.getMaskTexto(20);
            MaskFormatter mCidade = masc.getMaskTexto(25);
            MaskFormatter mCep = masc.getMaskCep();
            MaskFormatter mProfissao = masc.getMaskTexto(15);
            MaskFormatter mTelefonte = masc.getMaskTel();
            MaskFormatter mLogin = masc.getMaskTexto(20);
            mNome.install(jftfNome);
            mRua.install(jftfRua);
            mNroRua.install(jftfNroRua);
            mBairro.install(jftfBairro);
            mCidade.install(jftfCidade);
            mCep.install(jftfCEP);
            mProfissao.install(jftfProfissao);
            mTelefonte.install(jftfTelefone);
            mLogin.install(jftfLogin);
            masc.trim(jftfNome);
            masc.trim(jftfNroRua);
            masc.trim(jftfNroRua);
            masc.trim(jftfBairro);
            masc.trim(jftfCidade);
            masc.trim(jftfCEP);
            masc.trim(jftfProfissao);
            masc.trim(jftfTelefone);
            masc.trim(jftfLogin);
        } catch (ParseException ex) {
            Logger.getLogger(PnlOrientador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void validaCampo(JFormattedTextField f) {
        /*if (f.getText().trim().equals("")) {
            f.setText("0");
            f.setBackground(Color.green);
        } else {
            if (!(f.getText().equals("0"))) {
                f.setBackground(Color.white);
                f.setText(f.getText().toUpperCase());
            }
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLblMatricula = new javax.swing.JLabel();
        jLblRua = new javax.swing.JLabel();
        jLblNroRua = new javax.swing.JLabel();
        jLblBairro = new javax.swing.JLabel();
        jLblCidade = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jLblCEP = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jftfCEP = new javax.swing.JFormattedTextField();
        jLblProfissao = new javax.swing.JLabel();
        jLblUsuario = new javax.swing.JLabel();
        jLblSenha = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jftfMatricula = new javax.swing.JFormattedTextField();
        jftfNome = new javax.swing.JFormattedTextField();
        jftfCidade = new javax.swing.JFormattedTextField();
        jftfBairro = new javax.swing.JFormattedTextField();
        jftfRua = new javax.swing.JFormattedTextField();
        jftfProfissao = new javax.swing.JFormattedTextField();
        jftfLogin = new javax.swing.JFormattedTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jftfNroRua = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLblMatricula.setText("Matricula:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 15, 5);
        add(jLblMatricula, gridBagConstraints);

        jLblRua.setText("Endereço:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblRua, gridBagConstraints);

        jLblNroRua.setText("Nro Rua:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblNroRua, gridBagConstraints);

        jLblBairro.setText("Bairro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblBairro, gridBagConstraints);

        jLblCidade.setText("Cidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblCidade, gridBagConstraints);

        jLblTelefone.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblTelefone, gridBagConstraints);

        jLblCEP.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblCEP, gridBagConstraints);

        jLblNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblNome, gridBagConstraints);

        jftfCEP.setColumns(10);
        jftfCEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfCEPMouseClicked(evt);
            }
        });
        jftfCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfCEPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfCEPFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfCEP, gridBagConstraints);

        jLblProfissao.setText("Profissão:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLblProfissao, gridBagConstraints);

        jLblUsuario.setText("Login:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 10, 2);
        add(jLblUsuario, gridBagConstraints);

        jLblSenha.setText("Senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 10, 2);
        add(jLblSenha, gridBagConstraints);

        jPFSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPFSenhaMouseClicked(evt);
            }
        });
        jPFSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPFSenhaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 10, 2);
        add(jPFSenha, gridBagConstraints);

        jftfMatricula.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 15, 2);
        add(jftfMatricula, gridBagConstraints);

        jftfNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfNomeMouseClicked(evt);
            }
        });
        jftfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfNomeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfNome, gridBagConstraints);

        jftfCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfCidadeMouseClicked(evt);
            }
        });
        jftfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfCidadeFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfCidade, gridBagConstraints);

        jftfBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfBairroMouseClicked(evt);
            }
        });
        jftfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfBairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfBairroFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfBairro, gridBagConstraints);

        jftfRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfRuaMouseClicked(evt);
            }
        });
        jftfRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfRuaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfRua, gridBagConstraints);

        jftfProfissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfProfissaoMouseClicked(evt);
            }
        });
        jftfProfissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfProfissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfProfissaoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfProfissao, gridBagConstraints);

        jftfLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfLoginMouseClicked(evt);
            }
        });
        jftfLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfLoginFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 10, 2);
        add(jftfLogin, gridBagConstraints);

        jftfTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfTelefoneMouseClicked(evt);
            }
        });
        jftfTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfTelefoneFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfTelefone, gridBagConstraints);

        jftfNroRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftfNroRuaMouseClicked(evt);
            }
        });
        jftfNroRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jftfNroRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfNroRuaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jftfNroRua, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_painel_aluno.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jftfNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfNomeMouseClicked
        jftfNome.setText(jftfNome.getText().trim());
    }//GEN-LAST:event_jftfNomeMouseClicked

    private void jftfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNomeFocusGained
        jftfNome.setText(jftfNome.getText().trim());
    }//GEN-LAST:event_jftfNomeFocusGained

    private void jftfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNomeFocusLost
        jftfNome.setText(jftfNome.getText().trim());
        validaCampo(jftfNome);
    }//GEN-LAST:event_jftfNomeFocusLost

    private void jftfCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCidadeFocusGained
        jftfCidade.setText(jftfCidade.getText().trim());
    }//GEN-LAST:event_jftfCidadeFocusGained

    private void jftfCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCidadeFocusLost
        jftfCidade.setText(jftfCidade.getText().trim());
        validaCampo(jftfCidade);
    }//GEN-LAST:event_jftfCidadeFocusLost

    private void jftfCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfCidadeMouseClicked
        jftfCidade.setText(jftfCidade.getText().trim());
    }//GEN-LAST:event_jftfCidadeMouseClicked

    private void jftfBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfBairroFocusGained
        jftfBairro.setText(jftfBairro.getText().trim());
    }//GEN-LAST:event_jftfBairroFocusGained

    private void jftfBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfBairroFocusLost
        jftfBairro.setText(jftfBairro.getText().trim());
        validaCampo(jftfBairro);
    }//GEN-LAST:event_jftfBairroFocusLost

    private void jftfBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfBairroMouseClicked
        jftfBairro.setText(jftfBairro.getText().trim());
    }//GEN-LAST:event_jftfBairroMouseClicked

    private void jftfRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfRuaMouseClicked
        jftfRua.setText(jftfRua.getText().trim());
    }//GEN-LAST:event_jftfRuaMouseClicked

    private void jftfRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfRuaFocusGained
        jftfRua.setText(jftfRua.getText().trim());
    }//GEN-LAST:event_jftfRuaFocusGained

    private void jftfRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfRuaFocusLost
        jftfRua.setText(jftfRua.getText().trim());
        validaCampo(jftfRua);
    }//GEN-LAST:event_jftfRuaFocusLost

    private void jftfProfissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfProfissaoFocusGained
        jftfProfissao.setText(jftfProfissao.getText().trim());
    }//GEN-LAST:event_jftfProfissaoFocusGained

    private void jftfProfissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfProfissaoFocusLost
        jftfProfissao.setText(jftfProfissao.getText().trim());
        validaCampo(jftfProfissao);
    }//GEN-LAST:event_jftfProfissaoFocusLost

    private void jftfProfissaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfProfissaoMouseClicked
        jftfProfissao.setText(jftfProfissao.getText().trim());
    }//GEN-LAST:event_jftfProfissaoMouseClicked

    private void jftfLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfLoginMouseClicked
        jftfLogin.setText(jftfLogin.getText().trim());
    }//GEN-LAST:event_jftfLoginMouseClicked

    private void jftfLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfLoginFocusGained
        jftfLogin.setText(jftfLogin.getText().trim());
    }//GEN-LAST:event_jftfLoginFocusGained

    private void jftfLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfLoginFocusLost
        jftfLogin.setText(jftfLogin.getText().trim());
        validaCampo(jftfLogin);
    }//GEN-LAST:event_jftfLoginFocusLost

    private void jftfTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfTelefoneFocusGained
        jftfTelefone.setText(jftfTelefone.getText().trim());
    }//GEN-LAST:event_jftfTelefoneFocusGained

    private void jftfTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfTelefoneFocusLost
        jftfTelefone.setText(jftfTelefone.getText().trim());
        validaCampo(jftfTelefone);
    }//GEN-LAST:event_jftfTelefoneFocusLost

    private void jftfTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfTelefoneMouseClicked
        jftfTelefone.setText(jftfTelefone.getText().trim());
    }//GEN-LAST:event_jftfTelefoneMouseClicked

    private void jftfCEPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfCEPMouseClicked
        jftfCEP.setText(jftfCEP.getText().trim());
    }//GEN-LAST:event_jftfCEPMouseClicked

    private void jftfCEPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCEPFocusGained
        jftfCEP.setText(jftfCEP.getText().trim());
    }//GEN-LAST:event_jftfCEPFocusGained

    private void jftfCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCEPFocusLost
        jftfCEP.setText(jftfCEP.getText().trim());
        validaCampo(jftfCEP);
    }//GEN-LAST:event_jftfCEPFocusLost

    private void jftfNroRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNroRuaFocusGained
        jftfNroRua.setText(jftfNroRua.getText().trim());
    }//GEN-LAST:event_jftfNroRuaFocusGained

    private void jftfNroRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfNroRuaFocusLost
        jftfNroRua.setText(jftfNroRua.getText().trim());
        validaCampo(jftfNroRua);
    }//GEN-LAST:event_jftfNroRuaFocusLost

    private void jftfNroRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftfNroRuaMouseClicked
        jftfNroRua.setText(jftfNroRua.getText().trim());
    }//GEN-LAST:event_jftfNroRuaMouseClicked

    private void jPFSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFSenhaFocusGained
        jPFSenha.setText(jPFSenha.getText().trim());
    }//GEN-LAST:event_jPFSenhaFocusGained

    private void jPFSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFSenhaFocusLost
        jPFSenha.setText(jPFSenha.getText().trim());
        if (jPFSenha.getPassword().length == 0) {
            jPFSenha.requestFocus();
            jPFSenha.setBackground(Color.red);
            jPFSenha.setForeground(Color.white);
        } else {
            jPFSenha.setBackground(Color.white);
            jPFSenha.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPFSenhaFocusLost

    private void jPFSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPFSenhaMouseClicked
        jPFSenha.setText(jPFSenha.getText().trim());
    }//GEN-LAST:event_jPFSenhaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblMatricula;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNroRua;
    private javax.swing.JLabel jLblProfissao;
    private javax.swing.JLabel jLblRua;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JFormattedTextField jftfBairro;
    private javax.swing.JFormattedTextField jftfCEP;
    private javax.swing.JFormattedTextField jftfCidade;
    private javax.swing.JFormattedTextField jftfLogin;
    private javax.swing.JFormattedTextField jftfMatricula;
    private javax.swing.JFormattedTextField jftfNome;
    private javax.swing.JFormattedTextField jftfNroRua;
    private javax.swing.JFormattedTextField jftfProfissao;
    private javax.swing.JFormattedTextField jftfRua;
    private javax.swing.JFormattedTextField jftfTelefone;
    // End of variables declaration//GEN-END:variables

    public JLabel getJLblBairro() {
        return jLblBairro;
    }

    public void setJLblBairro(JLabel jLblBairro) {
        this.jLblBairro = jLblBairro;
    }

    public JLabel getJLblCEP() {
        return jLblCEP;
    }

    public void setJLblCEP(JLabel jLblCEP) {
        this.jLblCEP = jLblCEP;
    }

    public JLabel getJLblCidade() {
        return jLblCidade;
    }

    public void setJLblCidade(JLabel jLblCidade) {
        this.jLblCidade = jLblCidade;
    }

    public JLabel getJLblMatricula() {
        return jLblMatricula;
    }

    public void setJLblMatricula(JLabel jLblMatricula) {
        this.jLblMatricula = jLblMatricula;
    }

    public JLabel getJLblNome() {
        return jLblNome;
    }

    public void setJLblNome(JLabel jLblNome) {
        this.jLblNome = jLblNome;
    }

    public JLabel getJLblNroRua() {
        return jLblNroRua;
    }

    public void setJLblNroRua(JLabel jLblNroRua) {
        this.jLblNroRua = jLblNroRua;
    }

    public JLabel getJLblProfissao() {
        return jLblProfissao;
    }

    public void setJLblProfissao(JLabel jLblProfissao) {
        this.jLblProfissao = jLblProfissao;
    }

    public JLabel getJLblRua() {
        return jLblRua;
    }

    public void setJLblRua(JLabel jLblRua) {
        this.jLblRua = jLblRua;
    }

    public JLabel getJLblTelefone() {
        return jLblTelefone;
    }

    public void setJLblTelefone(JLabel jLblTelefone) {
        this.jLblTelefone = jLblTelefone;
    }

    public JFormattedTextField getJftCEP() {
        return jftfCEP;
    }

    public void setJftCEP(JFormattedTextField jftCEP) {
        this.jftfCEP = jftCEP;
    }

    public JFormattedTextField getJftTelefone() {
        return jftfTelefone;
    }

    public void setJftTelefone(JFormattedTextField jftTelefone) {
        this.jftfTelefone = jftTelefone;
    }

    public JFormattedTextField getJtfBairro() {
        return jftfBairro;
    }

    public void setJtfBairro(JFormattedTextField jtfBairro) {
        this.jftfBairro = jtfBairro;
    }

    public JFormattedTextField getJtfCidade() {
        return jftfCidade;
    }

    public void setJtfCidade(JFormattedTextField jtfCidade) {
        this.jftfCidade = jtfCidade;
    }

    public JFormattedTextField getJtfLogin() {
        return jftfLogin;
    }

    public void setJtfLogin(JFormattedTextField jtfLogin) {
        this.jftfLogin = jtfLogin;
    }

    public JFormattedTextField getJtfMatricula() {
        return jftfMatricula;
    }

    public void setJtfMatricula(JFormattedTextField jtfMatricula) {
        this.jftfMatricula = jtfMatricula;
    }

    public JFormattedTextField getJtfNome() {
        return jftfNome;
    }

    public void setJtfNome(JFormattedTextField jtfNome) {
        this.jftfNome = jtfNome;
    }

    public JFormattedTextField getJtfNroRua() {
        return jftfNroRua;
    }

    public void setJtfNroRua(JFormattedTextField jtfNroRua) {
        this.jftfNroRua = jtfNroRua;
    }

    public JFormattedTextField getJtfProfissao() {
        return jftfProfissao;
    }

    public void setJtfProfissao(JFormattedTextField jtfProfissao) {
        this.jftfProfissao = jtfProfissao;
    }

    public JFormattedTextField getJtfRua() {
        return jftfRua;
    }

    public void setJtfRua(JFormattedTextField jtfRua) {
        this.jftfRua = jtfRua;
    }

    public JPasswordField getjPFSenha() {
        return jPFSenha;
    }

    public void setjPFSenha(JPasswordField jPFSenha) {
        this.jPFSenha = jPFSenha;
    }

    public JLabel getjLblSenha() {
        return jLblSenha;
    }

    public void setjLblSenha(JLabel jLblSenha) {
        this.jLblSenha = jLblSenha;
    }

    public JLabel getjLblUsuario() {
        return jLblUsuario;
    }

    public void setjLblUsuario(JLabel jLblUsuario) {
        this.jLblUsuario = jLblUsuario;
    }
}
