/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 22/10/2009, 00:53:55
 */
package sapo.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JLabel;
import sapo.model.OrientadorModelo;
//import sapo.relatorios.Relatorios;
import sapo.util.Audio;
//import sapo.relatorios.Relatorios;

/**
 *
 * @author home
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    private OrientadorModelo orientador;

    public Principal() {
        initComponents();
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(tela.width, tela.height);
        this.setLocation((Principal.WIDTH - tela.width)/2,(Principal.HEIGHT - tela.height)/2);
        this.setLocation(0, 0);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        Date data = new Date();
        jlblData.setText(String.valueOf(data.toString()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnlJogos = new javax.swing.JPanel();
        jbtnJogoFiguras = new javax.swing.JButton();
        jbtnJogoFrutas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpnlCadRel = new javax.swing.JPanel();
        jpnlCadastro = new javax.swing.JPanel();
        jbtnResponsaveis = new javax.swing.JButton();
        jbtnCriancas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jpnlRelatorios = new javax.swing.JPanel();
        jbtnRelatórioAluno = new javax.swing.JButton();
        jbtnRelatórioAcompanhamento = new javax.swing.JButton();
        jbtnRelatórioOrientadores = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlblUsuario = new javax.swing.JLabel();
        jlblUser = new javax.swing.JLabel();
        jlblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAPO - Sistema de Apóio a Psicólogos e Orientadores");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmPrincipal"); // NOI18N

        jpnlJogos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlJogos.setLayout(new java.awt.GridBagLayout());

        jbtnJogoFiguras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_figGeo.png"))); // NOI18N
        jbtnJogoFiguras.setMnemonic('g');
        jbtnJogoFiguras.setToolTipText("Clique aqui para iniciar o jogo das Figuras Geométricas");
        jbtnJogoFiguras.setBorder(null);
        jbtnJogoFiguras.setBorderPainted(false);
        jbtnJogoFiguras.setContentAreaFilled(false);
        jbtnJogoFiguras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnJogoFigurasMouseEntered(evt);
            }
        });
        jbtnJogoFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJogoFigurasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(150, 5, 5, 5);
        jpnlJogos.add(jbtnJogoFiguras, gridBagConstraints);

        jbtnJogoFrutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_frutas.png"))); // NOI18N
        jbtnJogoFrutas.setMnemonic('c');
        jbtnJogoFrutas.setToolTipText("Clique aqui para iniciar o jogo de Frutas no Cesto");
        jbtnJogoFrutas.setBorder(null);
        jbtnJogoFrutas.setBorderPainted(false);
        jbtnJogoFrutas.setContentAreaFilled(false);
        jbtnJogoFrutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnJogoFrutasMouseEntered(evt);
            }
        });
        jbtnJogoFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJogoFrutasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jpnlJogos.add(jbtnJogoFrutas, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_jogos.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        jpnlJogos.add(jLabel2, gridBagConstraints);

        getContentPane().add(jpnlJogos, java.awt.BorderLayout.LINE_START);

        jpnlCadRel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlCadRel.setLayout(new java.awt.BorderLayout());

        jpnlCadastro.setLayout(new java.awt.GridBagLayout());

        jbtnResponsaveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_resp.png"))); // NOI18N
        jbtnResponsaveis.setMnemonic('r');
        jbtnResponsaveis.setToolTipText("Clique aqui para ir ao painel de cadastros de Professores, Orientadores e Psicólogos");
        jbtnResponsaveis.setBorder(null);
        jbtnResponsaveis.setBorderPainted(false);
        jbtnResponsaveis.setContentAreaFilled(false);
        jbtnResponsaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResponsaveisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jpnlCadastro.add(jbtnResponsaveis, gridBagConstraints);

        jbtnCriancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_crianças.png"))); // NOI18N
        jbtnCriancas.setMnemonic('s');
        jbtnCriancas.setToolTipText("Clique aqui para ir ao painel de cadastro de Crianças");
        jbtnCriancas.setBorder(null);
        jbtnCriancas.setBorderPainted(false);
        jbtnCriancas.setContentAreaFilled(false);
        jbtnCriancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCriancasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(150, 5, 5, 5);
        jpnlCadastro.add(jbtnCriancas, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_cadastro.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpnlCadastro.add(jLabel4, gridBagConstraints);

        jpnlCadRel.add(jpnlCadastro, java.awt.BorderLayout.NORTH);

        jpnlRelatorios.setLayout(new java.awt.GridBagLayout());

        jbtnRelatórioAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_alunos.png"))); // NOI18N
        jbtnRelatórioAluno.setMnemonic('t');
        jbtnRelatórioAluno.setToolTipText("Clique aqui para emitir os relatórios de acompanhamento das crianças");
        jbtnRelatórioAluno.setBorder(null);
        jbtnRelatórioAluno.setBorderPainted(false);
        jbtnRelatórioAluno.setContentAreaFilled(false);
        jbtnRelatórioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRelatórioAlunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(100, 5, 5, 5);
        jpnlRelatorios.add(jbtnRelatórioAluno, gridBagConstraints);

        jbtnRelatórioAcompanhamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_acompanhamento.png"))); // NOI18N
        jbtnRelatórioAcompanhamento.setMnemonic('t');
        jbtnRelatórioAcompanhamento.setToolTipText("Clique aqui para emitir os relatórios de acompanhamento das crianças");
        jbtnRelatórioAcompanhamento.setBorder(null);
        jbtnRelatórioAcompanhamento.setBorderPainted(false);
        jbtnRelatórioAcompanhamento.setContentAreaFilled(false);
        jbtnRelatórioAcompanhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRelatórioAcompanhamentoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(250, 5, 5, 5);
        jpnlRelatorios.add(jbtnRelatórioAcompanhamento, gridBagConstraints);

        jbtnRelatórioOrientadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_orientadores.png"))); // NOI18N
        jbtnRelatórioOrientadores.setMnemonic('t');
        jbtnRelatórioOrientadores.setToolTipText("Clique aqui para emitir os relatórios de acompanhamento das crianças");
        jbtnRelatórioOrientadores.setBorder(null);
        jbtnRelatórioOrientadores.setBorderPainted(false);
        jbtnRelatórioOrientadores.setContentAreaFilled(false);
        jbtnRelatórioOrientadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRelatórioOrientadoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(-50, 5, 5, 5);
        jpnlRelatorios.add(jbtnRelatórioOrientadores, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura_relatório.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpnlRelatorios.add(jLabel5, gridBagConstraints);

        jpnlCadRel.add(jpnlRelatorios, java.awt.BorderLayout.PAGE_END);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/textura.png"))); // NOI18N
        jpnlCadRel.add(jLabel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnlCadRel, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jlblUsuario.setText("Usuário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 0);
        jPanel1.add(jlblUsuario, gridBagConstraints);

        jlblUser.setText("user");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 300);
        jPanel1.add(jlblUser, gridBagConstraints);

        jlblData.setText("Data :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 300, 2, 2);
        jPanel1.add(jlblData, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Figura3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1206)/2, (screenSize.height-911)/2, 1206, 911);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCriancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCriancasActionPerformed
        new DlgCadAluno(this);
    }//GEN-LAST:event_jbtnCriancasActionPerformed

    private void jbtnResponsaveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResponsaveisActionPerformed
        new DlgCadOrientador(this);
    }//GEN-LAST:event_jbtnResponsaveisActionPerformed

    private void jbtnJogoFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJogoFigurasActionPerformed
        DlgJogoFigura jogo = new DlgJogoFigura(this, true, orientador);
    }//GEN-LAST:event_jbtnJogoFigurasActionPerformed

    private void jbtnJogoFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJogoFrutasActionPerformed
        DlgJogoFruta jogo = new DlgJogoFruta(this, true, orientador);
    }//GEN-LAST:event_jbtnJogoFrutasActionPerformed

    private void jbtnRelatórioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRelatórioAlunoActionPerformed
        try {
            //Relatorios rels = new Relatorios();
            //rels.visualizar("sapoaluno.jasper");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnRelatórioAlunoActionPerformed

    private void jbtnRelatórioAcompanhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRelatórioAcompanhamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRelatórioAcompanhamentoActionPerformed

    private void jbtnRelatórioOrientadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRelatórioOrientadoresActionPerformed
        // TODO add your handling code here:
       //Relatorios rels;
        try {
        //rels = new Relatorios();
        //rels.visualizar("sapoorientador.jasper");
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnRelatórioOrientadoresActionPerformed

    private void jbtnJogoFigurasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnJogoFigurasMouseEntered
        Audio a = new Audio();
        a.executa("/src/sons/fg.wav");        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnJogoFigurasMouseEntered

    private void jbtnJogoFrutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnJogoFrutasMouseEntered
        Audio a = new Audio();
        a.executa("/src/sons/fc.wav");        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnJogoFrutasMouseEntered
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCriancas;
    private javax.swing.JButton jbtnJogoFiguras;
    private javax.swing.JButton jbtnJogoFrutas;
    private javax.swing.JButton jbtnRelatórioAcompanhamento;
    private javax.swing.JButton jbtnRelatórioAluno;
    private javax.swing.JButton jbtnRelatórioOrientadores;
    private javax.swing.JButton jbtnResponsaveis;
    private javax.swing.JLabel jlblData;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPanel jpnlCadRel;
    private javax.swing.JPanel jpnlCadastro;
    private javax.swing.JPanel jpnlJogos;
    private javax.swing.JPanel jpnlRelatorios;
    // End of variables declaration//GEN-END:variables

    public JLabel getJlblUser() {
        return jlblUser;
    }

    public void setJlblUser(JLabel jlblUser) {
        this.jlblUser = jlblUser;
    }

    public OrientadorModelo getOrientador() {
        return orientador;
    }

    public void setOrientador(OrientadorModelo orientador) {
        this.orientador = orientador;
    }
}
